server:
  port: 8085
  forward-headers-strategy: native
#swaggerfox:
#  base-path: /docs
spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: storage-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/storage_service
app:
  api-key: b7>E9v#eQ!,UdbHEU*5]-vC<{j$3X`Pre`UpA2hz8CW%vBU-\NS66z3?f68w!pef
azure:
  storage:
    use-ssl: false
    connection-string: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;
    container-invoice: invoices